### ISSUE TITLE
Go report card doesn't render properly on the landing page + some of the links are broken

### ISSUE THREAD

**Issue by borisdali** [GoogleCloudPlatform/elcarro-oracle-operator#1]
1/ Go report card doesn't render properly:

Site cannot be reached: `https://goreportcard.com/report/github.com/GoogleCloudPlatform/elcarro-oracle-operator`

2/ All three links under https://github.com/GoogleCloudPlatform/elcarro-oracle-operator#backup-and-recovery are broken:

```
https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/blob/main/docs/content/backup-restore/snapshot-backups
https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/blob/main/docs/content/backup-restore/rman-backups
https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/blob/main/docs/content/backup-restore/restore-from-backups
```

All three are missing the .md suffix in the URL

Thanks,
Boris.

**Comment by borisdali** [comment]
The same applies to the `logging` link under `What's More?`, missing .md suffix in `https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/blob/main/docs/content/monitoring/logging`

**Comment by yian-zhou** [comment]
Thanks for reporting the link issue, Boris.

This is now fixed with https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/commit/c1f2852abf8ed54d5e8c80868e59946a8d4cbe9b. Cheers!
