### ISSUE TITLE
Podspec is only applied to the Oracle Statefulset, not to the Oracle Monitor Deployment

### ISSUE THREAD

**Issue by M-Schiefer** [GoogleCloudPlatform/elcarro-oracle-operator#377]
**Describe the bug**
Podspec is only applied to the Oracle Statefulset, not to the Oracle Monitor Deployment.
This causes the monitor pod to never be scheduled onto a node and forever stay in "Pending".

**To Reproduce**
Deploy an Instance with the following podSpec:
`  podSpec:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: workload
                  operator: In
                  values:
                    - app-instance
                - key: app
                  operator: In
                  values:
                    - oracle
              {{- if .Values.machineFamily }}
                - key: cloud.google.com/machine-family
                  operator: In
                  values:
                    - "{{ .Values.machineFamily }}"
              {{- end }}
    tolerations:
      - key: app
        value: oracle
        operator: Equal
        effect: NoSchedule
      - key: workload
        operator: Equal
        value: app-instance
        effect: NoSchedule`

Only the Oracle pod created by the Statefulset will have the tolerations and affinities applied to it. The Oracle monitor pod does not, but it does have a pod-affinity to the other pod.
This results in the monitor pod not being able to be scheduled onto a node, because it has to run on the same node as the other pod, but doesn't have the required toleration to be allowed onto that node.

**Expected behavior**
The podspec is applied to both pods.

**Comment by akinfermo** [comment]
Fixed by Pull request #380
