### ISSUE TITLE
image_build.sh script failing on Mac OS 11.3.1 with expr: syntax error

### ISSUE THREAD

**Issue by raekins** [GoogleCloudPlatform/elcarro-oracle-operator#4]
image_build.sh script failing on Mac OS 11.3.1 (bash & zsh shells) with expr: syntax error.

This is due to use of expr length e.g
% echo ${DBNAME}
PSTG

% echo `expr length "${DBNAME}"`
expr: syntax error

% echo "${#DBNAME}" 
4

Also, Mac OS does not include getopt so command line parameter parsing does not work on Mac OS.

**Comment by yian-zhou** [comment]
Thanks a lot for reporting the issue!

In the current El Carro release, local DB image build only works with Linux systems. Additional support for other operating systems like Mac OS will be added in future releases.

I've added a note to our user guide to clarify this. We'll be working on adding additional OS support and keep you updated. :-)

Meanwhile, if you'd like to continue testing El Carro, please feel free to test local image build with a Linux machine or the recommended approach of using Google Cloud Build (see [user guide](https://github.com/GoogleCloudPlatform/elcarro-oracle-operator/blob/main/docs/content/provision/image.md#using-google-cloud-build-to-create-a-containerized-oracle-database-image-recommended)).

Thanks a lot for trying out El Carro and your valuable feedback for improving El Carro! :-)

Cheers,
Yian
